-- Grzegorzverse defines

NDefines.NGame.END_DATE = "1867.1.2"
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 10
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 6
NDefines.NCountry.MINIMUM_POLICY_TIME = 5
NDefines.NCountry.UNREST_REVOLT_FACTOR = 0.4
NDefines.NCountry.LIBERTY_DESIRE_MERCANTILISM = 0.15
NDefines.NCountry.LIBERTY_DESIRE_GREAT_POWER_VASSAL = 30
NDefines.NCountry.PS_CHANGE_CULTURE = 5
NDefines.NAI.CHARTER_COMPANY_DEVELOPMENT_RELUCTANCE = 2
NDefines.NAI.CHARTER_COMPANY_BASE_RELUCTANCE = -2
NDefines.NEconomy.BASE_INTERESTS = 5.0
NDefines.NEconomy.LAND_TECH_MAINTENANCE_IMPACT = 0.06